In [2]:
import numpy as np

## Работа с numpy array

Создавать numpy.array можно из списка

In [7]:
array_from_list = np.array([1, 2, 3, 4, 5])
array_from_list

array([1, 2, 3, 4, 5])

In [74]:
array_from_lists = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_from_lists[0][0]

1

В numpy порой приходится создавать массивы из нулей или единиц

In [12]:
zeros_array = np.zeros((3, 3, 3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
zeros_like_a = np.zeros_like(array_from_lists)
zeros_like_a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Также можно быстро создавать единичную матрицу

In [14]:
eye_array = np.eye(4)
eye_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Если нужно создать массив с упорядоченными числами

In [15]:
arange_array = np.arange(10, 26, 2)
arange_array

array([10, 12, 14, 16, 18, 20, 22, 24])

In [16]:
linspace_array = np.linspace(0, 1, 9)
linspace_array

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

Преобразование размерностей

In [19]:
reshaped_array = arange_array.reshape((2, 4))
reshaped_array

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [21]:
raveled_array = reshaped_array.ravel()
raveled_array

array([10, 12, 14, 16, 18, 20, 22, 24])

In [20]:
flattened_array = reshaped_array.flatten()
flattened_array

array([10, 12, 14, 16, 18, 20, 22, 24])

In [24]:
zeros_array = np.zeros((3, 3, 3))
zeros_array.shape[2]

3

## Операции над матрицами

In [25]:
a = np.array([[0, 1], [2, 4]])
b = np.array([[-1, 3], [0, -1]])

In [26]:
a+b

array([[-1,  4],
       [ 2,  3]])

In [27]:
a-b

array([[ 1, -2],
       [ 2,  5]])

In [28]:
a*b

array([[ 0,  3],
       [ 0, -4]])

In [29]:
np.dot(a, b)

array([[ 0, -1],
       [-2,  2]])

In [30]:
a@b

array([[ 0, -1],
       [-2,  2]])

In [31]:
a.dot(b)

array([[ 0, -1],
       [-2,  2]])

In [32]:
np.linalg.inv(a)

array([[-2. ,  0.5],
       [ 1. ,  0. ]])

In [33]:
np.linalg.det(a)

-2.0

In [34]:
c = np.array([3, 1])
np.linalg.solve(a, c)

array([-5.5,  3. ])

In [41]:
d = np.array([-1, 2, 5])
e = np.array([-2, 0, 1])
np.sum(d*e)

7

In [42]:
np.sort(e)

array([-2,  0,  1])

## Работа со случайными числами

In [45]:
seed = 42

In [48]:
rng = np.random.default_rng(seed=seed)
rng.choice(np.array([-1, 0, 1]))

-1

In [ ]:
rng.choice()

In [52]:
rng.choice(5)

2

In [53]:
rng.random()

0.6973680290593639

In [56]:
rng.normal(0, 1)

0.12784040316728537

Legacy методы (не делайте так)

In [59]:
np.random.randint(10)

4

In [62]:
np.random.rand()

0.6982025108755355

## Базовые статистики

In [63]:
data = rng.normal(0, 1, 1000)

Выборочное среднее

In [64]:
data.mean()

-0.02627777534954081

Стандартное отклонение

In [65]:
data.std()

0.9855196837564155

Квантили

In [67]:
np.quantile(data, 0.75)

0.5898867452250403

In [68]:
np.median(data)

0.004504985818013596